schema-version: 1.0
name: aws-jdk 

persistent-dirs:
  - src:"{% srcDir %}":"{% user %}":.

const:
  product: amazon-corretto
  javaHome: "{% installDir %}/jdk"

var:
  version: "8"
  srcDir: /usr/src
  javaOptions:
  user: default

user: "{% user %}"
directory: "{% srcDir %}"
envs:
  - JAVA_TOOL_OPTIONS={% javaOptions %}

provision:
   - url: 
       from: https://corretto.aws/downloads/latest/{% product %}-{% version %}-x64-linux-jdk.tar.gz
       after: "{{ .templates }}/link.sh"
   - copy:
       from: "{{ .resources }}/java.security"
       todir: "{% javaHome %}/jre/lib/security"
   - env: JAVA_HOME={% javaHome %}
   - systempath: "$JAVA_HOME/bin"

command:
  javac: javac {{ .args }}
  java: java {{ .args }}

